"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { supabase } from "@/lib/supabase";
import Link from "next/link";

type Customer = { id: string; company: string };

type LineItem = {
  description: string;
  quantity: number;
  unitPrice: number;
};

const PRODUCT_SUGGESTIONS = [
  "MCB 63A 3-Phase",
  "Cable Tray 100mm x 50mm",
  "Switchgear Panel 400A",
  "Earth Leakage Circuit Breaker",
  "PVC Conduit 20mm (100m roll)",
  "Junction Box IP65",
  "LED Batten Light 36W",
  "Emergency Exit Light",
  "Industrial Motor Starter 15kW",
  "Transformer 100kVA",
  "HV Cable 3-Core 95mm²",
  "Solar PV Inverter 5kW",
  "UPS 10kVA Online",
  "PDU Rack Mount 16A",
  "DC Cable 6mm² (100m)",
];

export default function CreateQuoteForm({ customers }: { customers: Customer[] }) {
  const router = useRouter();
  const [selectedCustomer, setSelectedCustomer] = useState("");
  const [salesperson, setSalesperson] = useState("");
  const [notes, setNotes] = useState("");
  const [items, setItems] = useState<LineItem[]>([{ description: "", quantity: 1, unitPrice: 0 }]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [savedQuoteNo, setSavedQuoteNo] = useState<string | null>(null);

  const addRow = () => setItems([...items, { description: "", quantity: 1, unitPrice: 0 }]);
  const removeRow = (i: number) => setItems(items.filter((_, idx) => idx !== i));
  const updateItem = (i: number, field: keyof LineItem, value: string | number) =>
    setItems(items.map((item, idx) => (idx === i ? { ...item, [field]: value } : item)));

  const subtotals = items.map((it) => it.quantity * it.unitPrice);
  const grandTotal = subtotals.reduce((a, b) => a + b, 0);

  const validItems = items.filter((i) => i.description.trim() !== "");
  const canSubmit = selectedCustomer && salesperson && validItems.length > 0;

  async function handleSave(status: "Draft" | "Sent") {
    if (!canSubmit) return;
    setSaving(true);
    setError(null);

    try {
      // Insert quote — quote_no auto-generated by trigger
      const { data: quote, error: qErr } = await supabase
        .from("quotes")
        .insert({
          quote_no: "",
          customer_id: selectedCustomer,
          salesperson,
          status,
          notes: notes.trim() || null,
        })
        .select("id, quote_no")
        .single();

      if (qErr || !quote) throw new Error(qErr?.message ?? "Failed to create quote");

      // Insert line items
      const { error: iErr } = await supabase.from("quote_items").insert(
        validItems.map((item, idx) => ({
          quote_id: quote.id,
          description: item.description,
          quantity: item.quantity,
          unit_price: item.unitPrice,
          sort_order: idx,
        }))
      );

      if (iErr) throw new Error(iErr.message);

      setSavedQuoteNo(quote.quote_no);
    } catch (e: unknown) {
      setError(e instanceof Error ? e.message : "Something went wrong");
    } finally {
      setSaving(false);
    }
  }

  if (savedQuoteNo) {
    return (
      <div className="p-8 flex flex-col items-center justify-center min-h-[60vh]">
        <div className="w-16 h-16 rounded-full bg-emerald-900/50 border border-emerald-700 flex items-center justify-center mb-4">
          <svg className="w-8 h-8 text-emerald-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 12.75L11.25 15 15 9.75M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
        </div>
        <h2 className="text-xl font-semibold text-white mb-1">Quote Saved</h2>
        <p className="text-gray-400 text-sm mb-6">
          <span className="font-mono text-amber-400">{savedQuoteNo}</span> has been created and stored in the database.
        </p>
        <div className="flex gap-3">
          <button
            onClick={() => router.push("/quotes")}
            className="px-4 py-2 bg-amber-500 hover:bg-amber-400 text-gray-900 text-sm font-semibold rounded-lg transition-colors"
          >
            View All Quotes
          </button>
          <button
            onClick={() => {
              setSavedQuoteNo(null);
              setSelectedCustomer("");
              setSalesperson("");
              setNotes("");
              setItems([{ description: "", quantity: 1, unitPrice: 0 }]);
            }}
            className="px-4 py-2 bg-gray-800 hover:bg-gray-700 border border-gray-700 text-gray-300 text-sm font-medium rounded-lg transition-colors"
          >
            Create Another
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="p-8 max-w-4xl">
      <div className="mb-8">
        <h1 className="text-2xl font-semibold text-white">Create Quote</h1>
        <p className="text-gray-400 text-sm mt-1">New quote — saved as Draft or Sent</p>
      </div>

      {error && (
        <div className="mb-6 px-4 py-3 bg-red-900/30 border border-red-800 rounded-lg text-sm text-red-400">
          {error}
        </div>
      )}

      <div className="space-y-6">
        {/* Quote Details */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
          <h2 className="text-sm font-semibold text-gray-300 mb-4">Quote Details</h2>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <label className="block text-xs font-medium text-gray-400 mb-1.5">Quote Number</label>
              <input disabled value="Auto-generated on save" className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-500 cursor-not-allowed" />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-400 mb-1.5">Date</label>
              <input disabled value={new Date().toISOString().slice(0, 10)} className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-500 cursor-not-allowed" />
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-400 mb-1.5">
                Customer <span className="text-red-400">*</span>
              </label>
              <select
                value={selectedCustomer}
                onChange={(e) => setSelectedCustomer(e.target.value)}
                className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-200 focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500/30"
              >
                <option value="">— Select customer —</option>
                {customers.map((c) => (
                  <option key={c.id} value={c.id}>{c.company}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-xs font-medium text-gray-400 mb-1.5">
                Salesperson <span className="text-red-400">*</span>
              </label>
              <select
                value={salesperson}
                onChange={(e) => setSalesperson(e.target.value)}
                className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-200 focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500/30"
              >
                <option value="">— Select salesperson —</option>
                <option>Ahmad Faris</option>
                <option>Nurul Ain</option>
                <option>Boss</option>
              </select>
            </div>
          </div>
        </div>

        {/* Line Items */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
          <h2 className="text-sm font-semibold text-gray-300 mb-4">Line Items</h2>
          <div className="space-y-2">
            <div className="grid grid-cols-12 gap-2 mb-1">
              <div className="col-span-6 text-xs font-medium text-gray-500 uppercase tracking-wider px-1">Description</div>
              <div className="col-span-2 text-xs font-medium text-gray-500 uppercase tracking-wider px-1">Qty</div>
              <div className="col-span-2 text-xs font-medium text-gray-500 uppercase tracking-wider px-1">Unit Price (RM)</div>
              <div className="col-span-1 text-xs font-medium text-gray-500 uppercase tracking-wider px-1 text-right">Subtotal</div>
              <div className="col-span-1" />
            </div>
            {items.map((item, i) => (
              <div key={i} className="grid grid-cols-12 gap-2 items-center">
                <div className="col-span-6">
                  <input
                    list="products"
                    value={item.description}
                    onChange={(e) => updateItem(i, "description", e.target.value)}
                    placeholder="Product / service description"
                    className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500/30"
                  />
                </div>
                <div className="col-span-2">
                  <input
                    type="number" min={1} value={item.quantity}
                    onChange={(e) => updateItem(i, "quantity", Number(e.target.value))}
                    className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-200 focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500/30"
                  />
                </div>
                <div className="col-span-2">
                  <input
                    type="number" min={0} step={0.01} value={item.unitPrice}
                    onChange={(e) => updateItem(i, "unitPrice", Number(e.target.value))}
                    className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-200 focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500/30"
                  />
                </div>
                <div className="col-span-1 text-right">
                  <span className="text-sm font-medium text-gray-300">
                    {subtotals[i].toLocaleString("en-MY", { minimumFractionDigits: 2 })}
                  </span>
                </div>
                <div className="col-span-1 flex justify-center">
                  {items.length > 1 && (
                    <button onClick={() => removeRow(i)} className="w-7 h-7 rounded-md bg-gray-800 hover:bg-red-900/40 text-gray-600 hover:text-red-400 flex items-center justify-center transition-colors">
                      <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                        <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
                      </svg>
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
          <datalist id="products">
            {PRODUCT_SUGGESTIONS.map((p) => <option key={p} value={p} />)}
          </datalist>
          <button onClick={addRow} className="mt-4 flex items-center gap-1.5 text-xs font-medium text-amber-400 hover:text-amber-300 transition-colors">
            <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
              <path strokeLinecap="round" strokeLinejoin="round" d="M12 4.5v15m7.5-7.5h-15" />
            </svg>
            Add Row
          </button>
          <div className="mt-6 border-t border-gray-800 pt-4 flex justify-end">
            <div className="w-64 space-y-2">
              <div className="flex justify-between text-sm text-gray-400">
                <span>Subtotal</span>
                <span>RM {grandTotal.toLocaleString("en-MY", { minimumFractionDigits: 2 })}</span>
              </div>
              <div className="flex justify-between text-sm text-gray-400">
                <span>Tax (0%)</span>
                <span>RM 0.00</span>
              </div>
              <div className="flex justify-between text-base font-semibold text-white border-t border-gray-700 pt-2 mt-2">
                <span>Grand Total</span>
                <span className="text-amber-400">RM {grandTotal.toLocaleString("en-MY", { minimumFractionDigits: 2 })}</span>
              </div>
            </div>
          </div>
        </div>

        {/* Notes */}
        <div className="bg-gray-900 border border-gray-800 rounded-xl p-6">
          <h2 className="text-sm font-semibold text-gray-300 mb-4">Notes (Optional)</h2>
          <textarea
            rows={3} value={notes} onChange={(e) => setNotes(e.target.value)}
            placeholder="Payment terms, delivery notes, special conditions..."
            className="w-full bg-gray-800 border border-gray-700 rounded-lg px-3 py-2.5 text-sm text-gray-200 placeholder-gray-600 focus:outline-none focus:border-amber-500 focus:ring-1 focus:ring-amber-500/30 resize-none"
          />
        </div>

        {/* Actions */}
        <div className="flex items-center justify-between pt-2">
          <Link href="/quotes" className="text-sm text-gray-500 hover:text-gray-300 transition-colors">← Cancel</Link>
          <div className="flex gap-3">
            <button
              onClick={() => handleSave("Draft")}
              disabled={saving || !canSubmit}
              className="px-5 py-2.5 bg-gray-800 hover:bg-gray-700 disabled:opacity-40 disabled:cursor-not-allowed border border-gray-700 text-gray-300 text-sm font-medium rounded-lg transition-colors"
            >
              {saving ? "Saving…" : "Save as Draft"}
            </button>
            <button
              onClick={() => handleSave("Sent")}
              disabled={saving || !canSubmit}
              className="px-5 py-2.5 bg-amber-500 hover:bg-amber-400 disabled:opacity-40 disabled:cursor-not-allowed text-gray-900 text-sm font-semibold rounded-lg transition-colors"
            >
              {saving ? "Saving…" : "Save & Mark Sent"}
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
